# Main config
homeassistant:

  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_lat
  longitude: !secret home_lon
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 75

  # Units: metric for Metric, imperial for Imperial
  unit_system: metric

  # Timezone (from: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones)
  time_zone: Europe/Madrid

  # Packages
  packages:
    devices: !include packages/devices.yaml
    media: !include packages/media.yaml
    weather: !include packages/weather.yaml
    datetime: !include packages/datetime.yaml
    #tracking: !include packages/tracking.yaml

# Show links to resources in log and frontend
introduction:

# Track the sun
sun:

# Enables the frontend
frontend:

# HTTP configuration
http:
  api_password: !secret api_password
  use_x_forwarded_for: True
  #base_url: !secret base_url

# Log and debug
#logger:
#  default: critical
#  default: debug

# Recorder
recorder:
# Enables support for tracking state changes over time.
history:
# View all events in a logbook
logbook:


# Zones
zone:

  - name: Home
    latitude: !secret home_lat
    longitude: !secret home_lon
    radius: 100
    icon: mdi:home

  - name: Trabajo
    latitude: !secret work_lat
    longitude: !secret work_lon
    radius: 100
    icon: mdi:worker

# Groups
group: !include groups.yaml




