# Presence HASS Module
#
# Scripts and automations for "leaving home" event


automation:
- alias: Turn on music on light
  trigger:
    platform: state
    entity_id: switch.kitchen_light
    from: 'off'
    to: 'on'
  action:
    - service: script.play_music


script:

  play_music:
    sequence:

      #- condition: state
      #  entity_id: input_boolean.welcome_music
      #  state: 'on'

      - service: media_player.volume_set
        entity_id:
          - media_player.clementine_remote
        data_template:
          volume_level: "1.0"
      - service: media_player.media_play
        entity_id:
          - media_player.clementine_remote

      #- delay: 00:00:08

      #- service: tts.google_say
      #  entity_id: media_player.mpdlaptop
      #  data_template:
      #    message: "¡Hola Master Supremo! ¡Bienvenido!"


